tasks:
  - name: utils
    before: |
      sudo apt-get install tree
  - name: powershell
    # https://docs.aws.amazon.com/powershell/latest/userguide/pstools-getting-set-up-linux-mac.html
    # https://learn.microsoft.com/en-us/powershell/scripting/install/install-ubuntu?view=powershell-7.4
    before: |
      ./bin/powershell.sh
      # pwsh
      # Install-Module -Name AWS.Tools.Installer
      # Install-AWSToolsModule AWS.Tools.EC2,AWS.Tools.S3
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    before: |
      ./bin/aws-cli.sh
  - name: terraform
    before: |
      ./bin/terraform.sh
  - name: cdk
    before: |
      npm i -g aws-cdk
