#!/usr/bin/env bash

echo "=== delete objects ==="

if [ -z "$1" ]; then
    echo "there need bucket name. eg. ./bucket  bucketname"
    exit -1
fi

BUCKET_NAME=$1
echo $BUCKET_NAME
# https://awscli.amazonaws.com/v2/documentation/api/latest/reference/s3api/create-bucket.html
aws s3api list-objects \
--bucket $BUCKET_NAME \
--query Contents[].Key \
|jq -n '{Objects:[inputs | .[] | {Key: .}]}' > /tmp/delete.json

aws s3api delete-objects --bucket $BUCKET_NAME --delete file:///tmp/delete.json
